// Define an array of random acts of kindness
        const actsOfKindness = [
            "Smile at a stranger.",
            "Hold the door open for someone.",
            "Compliment a friend or family member.",
            "Donate to a local charity.",
            "Help a neighbor with their groceries.",
            "Send a thank-you note to someone who has helped you.",
            "Pay for the person behind you in the drive-thru.",
            "Pick up litter in your local park or neighborhood.",
            "Call a friend or family member you haven't talked to in a while to check in.",
            "Volunteer at a local soup kitchen or shelter.",
            "Plant a tree or flowers in a public space.",
            "Leave a kind note or message for someone to find.",
            "Offer your seat to someone in need on public transportation.",
            "Bake cookies and share them with your neighbors.",
            "Listen attentively when someone needs to talk.",
            "Help someone carry heavy bags or luggage.",
            "Compliment a stranger on their outfit or appearance.",
            "Hold an umbrella for someone when it's raining.",
            "Offer to walk a neighbor's dog.",
            "Send a care package to a deployed soldier.",
            "Donate old clothes or toys to a local charity.",
            "Write a positive online review for a small business.",
            "Give blood at a local blood drive.",
            "Tutor a student or help with homework.",
            "Cook a meal for a friend in need.",
            "Offer to mow a neighbor's lawn or shovel their snow.",
            "Buy coffee for the person behind you in line.",
            "Donate to a pet shelter or rescue organization.",
            "Pick up groceries for someone who can't leave their home.",
            "Send a care package to a nursing home.",
            "Offer to babysit for a busy parent.",
            "Hold a fundraiser for a charitable cause.",
            "Compliment a coworker's hard work.",
            "Donate books to a local library or school.",
            "Plant a garden and share the produce with neighbors.",
            "Visit a local nursing home to spend time with residents.",
            "Send a handwritten letter to a friend or family member.",
            "Offer your skills to a nonprofit organization.",
            "Help a stranger with directions or information.",
            "Leave a generous tip for your server or delivery person.",
            "Donate blankets or warm clothing to a homeless shelter.",
            "Let someone go ahead of you in line at the store.",
            "Offer to fix something for a friend or neighbor.",
            "Share a helpful article or resource with someone in need.",
            "Send a care package to a college student or military member.",
            "Compliment a parent on their well-behaved child.",
            "Donate food to a local food bank.",
            "Buy a meal for a homeless person.",
            "Help a friend move or organize their home.",
            "Visit an elderly neighbor and offer to run errands for them.",
            "Write a thank-you letter to your local first responders.",
            "Help a family in need with grocery shopping.",
            "Share a list of inspirational quotes with friends and family.",
            "Offer your time to mentor a student or young professional.",
            "Organize a neighborhood cleanup day.",
            "Donate school supplies to a local school in need.",
            "Create handmade cards for hospital patients.",
            "Offer free tutoring to students in your community.",
            "Surprise a friend with their favorite treat or snack.",
            "Support a local artist or musician by purchasing their work.",
            "Share a motivational book with a friend.",
            "Donate to a children's hospital or pediatric charity.",
            "Send flowers to a friend or family member just because.",
            "Help a friend with a home improvement project.",
            "Offer to walk or pet-sit for a neighbor's pet.",
            "Leave quarters at a laundromat for others to use.",
            "Send a care package to a deployed servicemember.",
            "Donate to an environmental charity or organization.",
            "Help an elderly neighbor with household chores.",
            "Leave a kind note in a library book for the next reader.",
            "Support a local animal shelter by volunteering or donating.",
            "Offer to teach a skill or hobby to a friend or neighbor.",
            "Buy a meal for a struggling family.",
            "Volunteer at a local youth organization or club.",
            "Donate gently used clothing to a thrift store.",
            "Send a heartfelt message to a loved one far away.",
            "Pay for a stranger's parking or bus fare.",
            "Organize a neighborhood carpool to reduce emissions.",
            "Help a coworker with a challenging project.",
            "Offer to drive a friend to a medical appointment.",
            "Contribute to a fundraiser for a medical expense.",
            "Donate to a disaster relief organization.",
            "Share your umbrella with someone on a rainy day.",
            "Offer to mentor a newcomer in your field or industry.",
            "Buy groceries for a struggling family.",
            "Donate to a clean water charity.",
            "Write a letter of appreciation to a teacher or mentor.",
            "Volunteer at a local community center or organization.",
            "Support a local small business by shopping there.",
            "Donate to a mental health charity or hotline.",
    "Smile at a stranger.",
    "Hold the door open for someone.",
    "Compliment a friend or family member.",
    "Donate to a local charity.",
    "Help a neighbor with their groceries.",
    "Send a thank-you note to someone who has helped you.",
    "Pay for the person behind you in the drive-thru.",
    "Pick up litter in your local park or neighborhood.",
    "Call a friend or family member you haven't talked to in a while to check in.",
    "Volunteer at a local soup kitchen or shelter.",
    "Plant a tree or flowers in a public space.",
    "Leave a kind note or message for someone to find.",
    "Offer your seat to someone in need on public transportation.",
    "Bake cookies and share them with your neighbors.",
    "Listen attentively when someone needs to talk.",
    "Help someone carry heavy bags or luggage.",
    "Compliment a stranger on their outfit or appearance.",
    "Hold an umbrella for someone when it's raining.",
    "Offer to walk a neighbor's dog.",
    "Send a care package to a deployed soldier.",
    "Donate old clothes or toys to a local charity.",
    "Write a positive online review for a small business.",
    "Give blood at a local blood drive.",
    "Tutor a student or help with homework.",
    "Cook a meal for a friend in need.",
    "Offer to mow a neighbor's lawn or shovel their snow.",
    "Buy coffee for the person behind you in line.",
    "Donate to a pet shelter or rescue organization.",
    "Pick up groceries for someone who can't leave their home.",
    "Send a care package to a nursing home.",
    "Offer to babysit for a busy parent.",
    "Hold a fundraiser for a charitable cause.",
    "Compliment a coworker's hard work.",
    "Donate books to a local library or school.",
    "Plant a garden and share the produce with neighbors.",
    "Visit a local nursing home to spend time with residents.",
    "Send a handwritten letter to a friend or family member.",
    "Offer your skills to a nonprofit organization.",
    "Help a stranger with directions or information.",
    "Leave a generous tip for your server or delivery person.",
    "Donate blankets or warm clothing to a homeless shelter.",
    "Let someone go ahead of you in line at the store.",
    "Offer to fix something for a friend or neighbor.",
    "Share a helpful article or resource with someone in need.",
    "Send a care package to a college student or military member.",
    "Compliment a parent on their well-behaved child.",
    "Donate food to a local food bank.",
    "Buy a meal for a homeless person.",
    "Help a friend move or organize their home.",
    "Visit an elderly neighbor and offer to run errands for them.",
    "Write a thank-you letter to your local first responders.",
    "Help a family in need with grocery shopping.",
    "Share a list of inspirational quotes with friends and family.",
    "Offer your time to mentor a student or young professional.",
    "Organize a neighborhood cleanup day.",
    "Donate school supplies to a local school in need.",
    "Create handmade cards for hospital patients.",
    "Offer free tutoring to students in your community.",
    "Surprise a friend with their favorite treat or snack.",
    "Support a local artist or musician by purchasing their work.",
    "Share a motivational book with a friend.",
    "Donate to a children's hospital or pediatric charity.",
    "Send flowers to a friend or family member just because.",
    "Help a friend with a home improvement project.",
    "Offer to walk or pet-sit for a neighbor's pet.",
    "Leave quarters at a laundromat for others to use.",
    "Send a care package to a deployed servicemember.",
    "Donate to an environmental charity or organization.",
    "Help an elderly neighbor with household chores.",
    "Leave a kind note in a library book for the next reader.",
    "Support a local animal shelter by volunteering or donating.",
    "Offer to teach a skill or hobby to a friend or neighbor.",
    "Buy a meal for a struggling family.",
    "Volunteer at a local youth organization or club.",
    "Donate gently used clothing to a thrift store.",
    "Send a heartfelt message to a loved one far away.",
    "Pay for a stranger's parking or bus fare.",
    "Organize a neighborhood carpool to reduce emissions.",
    "Help a coworker with a challenging project.",
    "Offer to drive a friend to a medical appointment.",
    "Contribute to a fundraiser for a medical expense.",
    "Donate to a disaster relief organization.",
    "Share your umbrella with someone on a rainy day.",
    "Offer to mentor a newcomer in your field or industry.",
    "Buy groceries for a struggling family.",
    "Donate to a clean water charity.",
    "Write a letter of appreciation to a teacher or mentor.",
    "Volunteer at a local community center or organization.",
    "Support a local small business by shopping there.",
    "Donate to a mental health charity or hotline.",
    "Offer to give someone a ride who needs transportation.",
    "Leave an uplifting note on someone's windshield.",
    "Support a friend's creative project or business venture.",
    "Help someone carry heavy bags up a flight of stairs.",
    "Buy a meal for a police officer or firefighter.",
    "Offer to help a parent with their children at the park.",
    "Leave a kind comment on a friend's social media post.",
    "Support a friend or family member's personal goal or dream.",
    "Donate to a cancer research organization.",
    "Offer to pick up prescriptions for an elderly neighbor.",
    "Leave a generous tip for your barista.",
    "Offer to help a coworker with their workload.",
    "Donate to a wildlife conservation organization.",
    "Share a favorite recipe with a friend or family member.",
    "Offer to assist someone with their technology or computer issues.",
    "Help a neighbor with their yard work or gardening.",
    "Donate to a human rights or social justice organization.",
    "Support a homeless shelter or outreach program.",
    "Offer to help a friend with a home improvement project.",
    "Leave a kind note for your mail carrier or delivery person.",
    "Pay for a stranger's parking meter.",
    "Donate to a local arts or cultural organization.",
    "Support a friend or family member's educational pursuit.",
    "Offer to help an elderly neighbor with household maintenance.",
];

// Function to generate a random act of kindness
function generateRandomAct() {
    const randomIndex = Math.floor(Math.random() * actsOfKindness.length);
    const randomAct = actsOfKindness[randomIndex];
    document.getElementById("actOfKindness").textContent = randomAct;
}
